name: Deploy Vercel

on:
  push:
    branches:
      - principal

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm


      - name: Instalar dependências
        run: npm ci


      - name: Rodar ESLint
        run: npm run lint


      - name: Rodar testes
        run: npm run test:ci


      - name: Build
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy Vercel
        run: npx vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }}